### PR TITLE
fix(packages) Added global entrypoint type

### LINKED ISSUE #402: inject allowLinker setting
# TL;DR

before 

```js
new Agent('id', { alloLinker: true })
```

```js
new Agent('id', 'auto', { alloLinker: true })
```

## Backward compatibility

breaking changes

### PR DESCRIPTION
**Pull request by 9renpoto**
# TL;DR

Closes #402 

refs; https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google.analytics/index.d.ts

### CODE REVIEW

File: packages/userdive/src/types.ts [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+  metric13?: string | number
+  metric14?: string | number
+  metric15?: string | number
+  metric16?: string | number
+  metric17?: string | number
+  metric18?: string | number
+  metric19?: string | number
+  metric20?: string | number
+  name?: string
+  // useBeacon?: boolean
```
Comment (9renpoto) [inline packages/userdive/src/types.ts]: feature ?

File: .circleci/config.yml [hunk 2]
```diff
@@ -28,3 +36,9 @@ workflows:
                 - master
     jobs:
       - test
+      - deploy:
```
Comment (9renpoto) [inline .circleci/config.yml]: https://circleci.com/docs/2.0/deployment-integrations/
